--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lacum/.config/wallpaper/basquiat-art9.jpg"

-- Special
background="#22190e"
foreground="#c7c5c2"
cursor="#c7c5c2"

-- Colors
color0="#22190e"
color1="#60708A"
color2="#55B5A9"
color3="#A4A69F"
color4="#C9B6AD"
color5="#D9CCB5"
color6="#DED7CA"
color7="#c7c5c2"
color8="#72695e"
color9="#60708A"
color10="#55B5A9"
color11="#A4A69F"
color12="#C9B6AD"
color13="#D9CCB5"
color14="#DED7CA"
color15="#c7c5c2"
