[colors]
background = '#22190e8e'
black = '#22190e'
blue = '#60708A'
cursor = '#c7c5c2'
cyan = '#55B5A9'
foreground = '#c7c5c2'
green = '#A4A69F'
magenta = '#C9B6AD'
red = '#D9CCB5'
tabs = '#c7c5c2'
tabs-active = '#DED7CA'
white = '#c7c5c2'
yellow = '#c7c5c2'
dim-black = '#22190e8e'
dim-blue = '#60708A8e'
dim-cyan = '#55B5A98e'
dim-foreground = '#c7c5c28e'
dim-green = '#A4A69F8e'
dim-magenta = '#C9B6AD8e'
dim-red = '#D9CCB58e'
dim-white = '#DED7CA8e'
dim-yellow = '#c7c5c28e'
light-black = '#60708A'
light-blue = '#55B5A9'
light-cyan = '#A4A69F'
light-foreground = '#C9B6AD'
light-green = '#D9CCB5'
light-magenta = '#DED7CA'
light-red = '#c7c5c2'
light-white = '#60708A'
light-yellow = '#55B5A9'
