--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lacum/.config/wallpaper/wallpaper.png"

-- Special
background="#0F2237"
foreground="#ccdccf"
cursor="#ccdccf"

-- Colors
color0="#0F2237"
color1="#3B8893"
color2="#518D93"
color3="#679E9C"
color4="#75A9A4"
color5="#91B19D"
color6="#8CB7A9"
color7="#ccdccf"
color8="#8e9a90"
color9="#3B8893"
color10="#518D93"
color11="#679E9C"
color12="#75A9A4"
color13="#91B19D"
color14="#8CB7A9"
color15="#ccdccf"
