# Shell variables
# Generated by 'wal'
wallpaper="/home/lacum/.config/wallpaper/basquiat-art9.jpg"

# Special
background='#22190e'
foreground='#c7c5c2'
cursor='#c7c5c2'

# Colors
color0='#22190e'
color1='#60708A'
color2='#55B5A9'
color3='#A4A69F'
color4='#C9B6AD'
color5='#D9CCB5'
color6='#DED7CA'
color7='#c7c5c2'
color8='#72695e'
color9='#60708A'
color10='#55B5A9'
color11='#A4A69F'
color12='#C9B6AD'
color13='#D9CCB5'
color14='#DED7CA'
color15='#c7c5c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
